export const GET_PRODUCT_BYID_SUCCESS = "GET_PRODUCT_BYID_SUCCESS"
export const GET_PRODUCT_BYID_FAIL = "GET_PRODUCT_BYID_FAIL"
export const GET_PRODUCT_BYID_REQUEST = "GET_PRODUCT_BYID_REQUEST"


export const GET_TOP_RATED_PRODUCTS_REQUEST = "GET_TOP_RATED_PRODUCTS_REQUEST"
export const GET_TOP_RATED_PRODUCTS_FAIL = "GET_TOP_RATED_PRODUCTS_FAIL"
export const GET_TOP_RATED_PRODUCTS_SUCCESS = "GET_TOP_RATED_PRODUCTS_SUCCESS"

export const GET_MOST_DOWNLOADED_PRODUCTS_REQUEST = "GET_MOST_DOWNLOADED_PRODUCTS_REQUEST"
export const GET_MOST_DOWNLOADED_PRODUCTS_FAIL = "GET_MOST_DOWNLOADED_PRODUCTS_FAIL"
export const GET_MOST_DOWNLOADED_PRODUCTS_SUCCESS = "GET_MOST_DOWNLOADED_PRODUCTS_SUCCESS"

export const GET_YOUNGEST_PRODUCTS_REQUEST = "GET_YOUNGEST_PRODUCTS_REQUEST"
export const GET_YOUNGEST_PRODUCTS_FAIL = "GET_YOUNGEST_PRODUCTS_FAIL"
export const GET_YOUNGEST_PRODUCTS_SUCCESS = "GET_YOUNGEST_PRODUCTS_SUCCESS"

export const GET_OLDEST_PRODUCTS_REQUEST = "GET_OLDEST_PRODUCTS_REQUEST"
export const GET_OLDEST_PRODUCTS_FAIL = "GET_OLDEST_PRODUCTS_FAIL"
export const GET_OLDEST_PRODUCTS_SUCCESS = "GET_OLDEST_PRODUCTS_SUCCESS"


export const GET_PRODUCTS_SEARCHED_SUCCESS = "GET_PRODUCTS_SEARCHED_SUCCESS"
export const GET_PRODUCTS_SEARCHED_FAIL = "GET_PRODUCTS_SEARCHED_FAIL"
export const GET_PRODUCTS_SEARCHED_REQUEST = "GET_PRODUCTS_SEARCHED_REQUEST"


export const ADD_COINS_SUCCESS = "ADD_COINS_SUCCESS"
export const ADD_COINS_FAIL = "ADD_COINS_FAIL"
export const ADD_COINS_REQUEST = "ADD_COINS_REQUEST"

export const REMOVE_COINS_SUCCESS = "REMOVE_COINS_SUCCESS"
export const REMOVE_COINS_FAIL = "REMOVE_COINS_FAIL"
export const REMOVE_COINS_REQUEST = "REMOVE_COINS_REQUEST"


export const GET_PRICES_REQUEST = "GET_PRICES_REQUEST"
export const GET_PRICES_SUCCESS = "GET_PRICES_SUCCESS"
export const GET_PRICES_FAIL = "GET_PRICES_FAIL"

export const POST_PRICE_REQUEST = "POST_PRICE_REQUEST"
export const POST_PRICE_SUCCESS = "POST_PRICE_SUCCESS"
export const POST_PRICE_FAIL = "POST_PRICE_FAIL"


export const DELETE_PRICE_REQUEST = "DELETE_PRICE_REQUEST"
export const DELETE_PRICE_SUCCESS = "DELETE_PRICE_SUCCESS"
export const DELETE_PRICE_FAIL = "DELETE_PRICE_FAIL"


export const DELETE_ALL_PRICE_REQUEST = "DELETE_ALL_PRICE_REQUEST"
export const DELETE_ALL_PRICE_SUCCESS = "DELETE_ALL_PRICE_SUCCESS"
export const DELETE_ALL_PRICE_FAIL = "DELETE_ALL_PRICE_FAIL"


export const ADD_TO_WISH_LIST_REQUEST = "ADD_TO_WISH_LIST_REQUEST"
export const ADD_TO_WISH_LIST_SUCCESS = "ADD_TO_WISH_LIST_SUCCESS"
export const ADD_TO_WISH_LIST_FAIL = "ADD_TO_WISH_LIST_FAIL"


export const UPDATE_USER_PREFERENCES_REQUEST = "UPDATE_USER_PREFERENCES_REQUEST"
export const UPDATE_USER_PREFERENCES_SUCCESS = "UPDATE_USER_PREFERENCES_SUCCESS"
export const UPDATE_USER_PREFERENCES_FAIL = "UPDATE_USER_PREFERENCES_FAIL"


export const REMOVE_FROM_WISHLIST_REQUEST = "REMOVE_FROM_WISHLIST_REQUEST"
export const REMOVE_FROM_WISHLIST_SUCCESS = "REMOVE_FROM_WISHLIST_SUCCESS"
export const REMOVE_FROM_WISHLIST_FAIL = "REMOVE_FROM_WISHLIST_FAIL"