export const GET_USER_BYID_REQUEST = "GET_USER_BYID_REQUEST"
export const GET_USER_BYID_SUCCESS = "GET_USER_BYID_SUCCESS"
export const GET_USER_BYID_FAIL ="GET_USER_BYID_FAIL"

export const UPDATE_USER_BYID_REQUEST = "UPDATE_USER_BYID_REQUEST"
export const UPDATE_USER_BYID_SUCCESS = "UPDATE_USER_BYID_SUCCESS"
export const UPDATE_USER_BYID_FAIL ="UPDATE_USER_BYID_FAIL"
