# Generated by Django 5.0.4 on 2024-04-23 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.FloatField()),
                ("expireDate", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("price", models.FloatField()),
                ("age", models.IntegerField(blank=True, null=True)),
                ("company", models.CharField(max_length=60)),
                ("description", models.TextField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("downloads", models.FloatField(blank=True, null=True)),
                ("memory", models.FloatField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "introductionVideo",
                    models.FileField(blank=True, null=True, upload_to="videos/%y"),
                ),
                (
                    "multiplayer",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Gamesapp.gamesale",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, null=True, to="Gamesapp.tag"),
                ),
            ],
        ),
    ]
