# Generated by Django 5.0.4 on 2024-05-07 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gamesapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="age",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="downloads",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="rating",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(5.0)],
            ),
        ),
    ]
