# Generated by Django 5.0.4 on 2026-08-12 13:27

import django.db.models.deletion
from django.db import migrations, models


def copy_images_forward(apps, schema_editor):
    Game = apps.get_model('Gamesapp', 'Game')
    GameImage = apps.get_model('Gamesapp', 'GameImage')
    for game in Game.objects.exclude(image__isnull=True).exclude(image__exact=''):
        GameImage.objects.create(game=game, image=game.image)


def copy_images_backward(apps, schema_editor):
    Game = apps.get_model('Gamesapp', 'Game')
    GameImage = apps.get_model('Gamesapp', 'GameImage')
    for game in Game.objects.all():
        first_image = GameImage.objects.filter(game=game).first()
        if first_image:
            game.image = first_image.image
            game.save(update_fields=['image'])


class Migration(migrations.Migration):

    dependencies = [
        ('Gamesapp', '0002_alter_game_age_alter_game_downloads_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='games/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Gamesapp.game')),
            ],
        ),
        migrations.RunPython(copy_images_forward, copy_images_backward),
        migrations.RemoveField(
            model_name='game',
            name='image',
        ),
    ]
