# Generated by Django 5.0.4 on 2026-08-12 13:32

import django.db.models.deletion
from django.db import migrations, models


def copy_videos_forward(apps, schema_editor):
    Game = apps.get_model('Gamesapp', 'Game')
    GameVideo = apps.get_model('Gamesapp', 'GameVideo')
    for game in Game.objects.exclude(introductionVideo__isnull=True).exclude(introductionVideo__exact=''):
        GameVideo.objects.create(game=game, video=game.introductionVideo)


def copy_videos_backward(apps, schema_editor):
    Game = apps.get_model('Gamesapp', 'Game')
    GameVideo = apps.get_model('Gamesapp', 'GameVideo')
    for game in Game.objects.all():
        first_video = GameVideo.objects.filter(game=game).first()
        if first_video:
            game.introductionVideo = first_video.video
            game.save(update_fields=['introductionVideo'])


class Migration(migrations.Migration):

    dependencies = [
        ('Gamesapp', '0003_remove_game_image_gameimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/%y')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Gamesapp.game')),
            ],
        ),
        migrations.RunPython(copy_videos_forward, copy_videos_backward),
        migrations.RemoveField(
            model_name='game',
            name='introductionVideo',
        ),
    ]
