# Generated by Django 5.0.4 on 2024-05-07 09:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Gamesapp", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(blank=True, max_length=30, null=True)),
                ("numberOfGames", models.IntegerField(blank=True, null=True)),
                (
                    "coins",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                    ),
                ),
                ("genre", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "games",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="games_of_the_user",
                        to="Gamesapp.game",
                    ),
                ),
            ],
        ),
    ]
