# Generated by Django 5.0.4 on 2024-05-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Usersapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.CharField(
                blank=True,
                default="../static/default-user.png",
                max_length=100,
                null=True,
            ),
        ),
    ]
