# Generated by Django 5.0.4 on 2024-05-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Usersapp", "0002_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.CharField(
                blank=True, default="default_user.png", max_length=100, null=True
            ),
        ),
    ]
