# Generated by Django 5.0.4 on 2024-05-09 15:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Usersapp", "0003_alter_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="numberOfGames",
        ),
        migrations.AddField(
            model_name="profile",
            name="bought_games_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, null=True, size=None
            ),
        ),
    ]
