# Generated by Django 5.0.4 on 2024-05-09 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Usersapp", "0004_remove_profile_numberofgames_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="bought_games_ids",
            new_name="bought_games",
        ),
    ]
