# Generated by Django 5.0.4 on 2024-05-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Usersapp", "0005_rename_bought_games_ids_profile_bought_games"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bought_games",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
