# Generated by Django 5.0.4 on 2026-08-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usersapp', '0006_alter_profile_bought_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
