# Generated by Django 5.0.4 on 2026-08-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usersapp', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('developer', 'Developer'), ('moderator', 'Moderator'), ('support', 'Support'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
