# Generated by Django 5.0.4 on 2026-08-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamesapp', '0004_remove_game_introductionvideo_gamevideo'),
        ('Usersapp', '0008_profile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='games',
        ),
        migrations.AddField(
            model_name='profile',
            name='wished_games',
            field=models.ManyToManyField(blank=True, related_name='wished_by_users', to='Gamesapp.game'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bought_games',
        ),
        migrations.AddField(
            model_name='profile',
            name='bought_games',
            field=models.ManyToManyField(blank=True, related_name='owned_by_users', to='Gamesapp.game'),
        ),
    ]
