# Generated by Django 5.0.4 on 2024-05-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("money", models.FloatField(default=0)),
                ("coins", models.FloatField(default=0)),
                ("bonus", models.FloatField(default=0)),
                ("priceId", models.CharField(default="default_value", max_length=50)),
            ],
        ),
    ]
