# Generated by Django 5.0.4 on 2024-05-07 09:47

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("UsersPaymentApp", "0001_initial"),
        ("Usersapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilePayments",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("Usersapp.profile",),
        ),
    ]
