# Generated by Django 5.0.4 on 2024-04-23 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Gamesapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("likes", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(default="")),
                ("createDate", models.DateTimeField(auto_now_add=True)),
                ("updateDate", models.DateTimeField(auto_now=True)),
                (
                    "idGame",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="Gamesapp.game"
                    ),
                ),
                (
                    "idUser",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileGameRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gameId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="Gamesapp.game"
                    ),
                ),
                (
                    "userId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
